### ISSUE TITLE
Not showing Schedule a publish date on multisite

### ISSUE THREAD

**Issue by PopaWeb** [Goldinteractive/craft3-publisher#7] opened 2021-04-28 15:42 UTC
Hi,

Works great for the Primary site, but using multisite the Schedule a publish date section (on the right) is not showing when a draft exist on the secondary site.

I have tried with two different site settings:
1. Both site sharing the same page section
2. Independent page section for each site

Same result: Schedule a publish date section not showing on secondary site.

Craft Pro 3.6.12 
Publisher 2.0.5

**Comment by lukasNo1** [comment] 2021-04-30 10:37
I could reproduce the issue on independent page sections (2). Not on shared sections though.

We will have a look at this problem.

**Comment by PopaWeb** [comment] 2021-04-30 12:24
Thank you! 
Hope you find this bug.
If you need more info, let me know.
I really love this plugin.

**Comment by lukasNo1** [comment] 2021-05-12 15:16
I fixed the issue for independent site sections in the new release [2.0.6](https://github.com/Goldinteractive/craft3-publisher/releases/tag/2.0.6).

I could not reproduce the other issue. Could you test if the issue for your shared sections is also fixed in this new release?

**Comment by PopaWeb** [comment] 2021-05-12 17:17
Thanks!
I will test it and get back to you.

**Comment by PopaWeb** [comment] 2021-05-12 19:00
Hi,

In both site sharing the same page section; only the first created draft is showing on the right sire panel, even if there is 2 drafts for the same entry and site or 1 draft for each site for the same entry

**Comment by lukasNo1** [comment] 2021-05-18 09:24
The only thing i could think of where a draft is not shown is if the entry is deactivated for the site in this draft.

So if you have 2 drafts and in draft nr. 2 the entry is deactivated for your site, you won't see draft 2 on the right side.

This would be a fast change if thats a problem, we just need to show deactivated drafts too.
Can you check if this is the case for your site?

**Closed as completed** 2022-03-30 09:22 UTC
Labels: bug
